version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: nearbychat-postgis
    environment:
      POSTGRES_USER: nearbychat
      POSTGRES_PASSWORD: nearbychat_pass
      POSTGRES_DB: nearbychat_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
